python ./test1.py 
Traceback (most recent call last):
  File "/home/anupam/miniconda3py38/lib/python3.8/site-packages/gymnasium/envs/box2d/bipedal_walker.py", line 15, in <module>
    import Box2D
ModuleNotFoundError: No module named 'Box2D'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./test1.py", line 4, in <module>
    env = gym.make("LunarLander-v2", "human")
  File "/home/anupam/miniconda3py38/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 756, in make
    env_creator = load_env_creator(env_spec.entry_point)
  File "/home/anupam/miniconda3py38/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 545, in load_env_creator
    mod = importlib.import_module(mod_name)
  File "/home/anupam/miniconda3py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/anupam/miniconda3py38/lib/python3.8/site-packages/gymnasium/envs/box2d/__init__.py", line 1, in <module>
    from gymnasium.envs.box2d.bipedal_walker import BipedalWalker, BipedalWalkerHardcore
  File "/home/anupam/miniconda3py38/lib/python3.8/site-packages/gymnasium/envs/box2d/bipedal_walker.py", line 25, in <module>
    raise DependencyNotInstalled(
gymnasium.error.DependencyNotInstalled: Box2D is not installed, run `pip install gymnasium[box2d]`


(this is after I commented the render="human" error and just passed "human" i.e. the error that var = expression as func arguement wasn't working)

then : 

python ./test1.py 
Traceback (most recent call last):
  File "./test1.py", line 9, in <module>
    observation, reward, terminated, truncated, info = env.step(action) # (observe the env-state, reward) 
  File "/home/anupam/miniconda3py38/lib/python3.8/site-packages/gymnasium/wrappers/time_limit.py", line 60, in step
    if self._elapsed_steps >= self._max_episode_steps:
TypeError: '>=' not supported between instances of 'int' and 'str'

--> fixed, just had to replace render-mode with render_mode, duh..



